---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sawsecrtokenupdater-cm
  namespace: ggeply
data:
  AWS_REGION: "us-east-1" # Replace with your ECR region
  DOCKER_SECRET_NAME: ecr-secret # Replace with your desired ECR token secret name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sawsecrtokenupdater-sa
  namespace: ggeply
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ggeply
  name: role-full-access-to-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ecr-secret"] # Replace with your desired ECR token secret name
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-role-binding
  namespace: ggeply
subjects:
- kind: ServiceAccount
  name: k8sawsecrtokenupdater-sa # Replace with your service account name if different
  namespace: ggeply 
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets # Replace with your role name if different 
  apiGroup: ""
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8sawsecrtokenupdater-cj
  namespace: ggeply
spec:
  schedule: "0 */10 * * *" # Replace with your desired schedule
  successfulJobsHistoryLimit: 2
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k8sawsecrtokenupdater-sa # Replace with your service account name if different
          containers:
          - name: k8sawsecrtokenupdater-job
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: aws-secret # Replace with your secret name if different
              - configMapRef:
                  name: k8sawsecrtokenupdater-cm # Replace with your configmap name if different
            command:
              - /bin/sh
              - -c
              - |-
                ECR_TOKEN="$(aws ecr get-login-password --region ${AWS_REGION})"
                NAMESPACE_NAME=ggeply # Replace with your desired namespace
                kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME -n $NAMESPACE_NAME
                kubectl create secret docker-registry $DOCKER_SECRET_NAME --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com --docker-username=AWS --docker-password=${ECR_TOKEN} --namespace=$NAMESPACE_NAME
                echo "Secret was successfully updated at $(date)"
          restartPolicy: Never